### ISSUE TITLE
Question: If JS disabled by domain, some sites dont work

### ISSUE THREAD

**Issue by sir-harlekin** [dpacassi/disable-javascript#33] opened 2018-08-21 10:56 UTC
Hi there,

maybe i am just missing something:

If i use blocking per domain for example amazon does not work. i guess its because some of the underlying domains (amazon pictures and what not) are not greenlit.

It works if i chose blocking by tab.

Is there a way to greenlight all "invisible" domains belonging to the TLD?

Kind regards

**Comment by dpacassi** [comment] 2018-08-30 12:59
Hey @sir-harlekin!

Thanks for your question. Actually, if you open the web extension settings page (right click on the switch icon and select `Open Disable JS settings`, you can remove the `www.amazon.com` entry and add a `amazon.com` entry with `Include sub-domains?` **checked**.
That way you can whitelist/blacklist all subdomains belonging to one TLD.

This should solve your issue.
However, I find it interesting that Amazon works for you if you block things by tab but not if you block it via domain.
For me it works in both cases.
And reviewing my code, there's no difference in how to block JS for either case.

I would like to inspect this behavior a bit more. Could you please define which Amazon URL does not work for you if you disable JS by domain? And maybe not just the URL but also what exactly you expect to work (which functionality).
Also, a screenshot of your Disable JavaScript settings would be great :)

Thanks for your help!

**Comment by ugulz** [comment] 2018-09-24 12:27
I have same problem with some sites not fully working if using "by domain".  It only work properly if using "by tab" or disabling extension altogether.  The one I was just using was  ebay.com.au creating a listing the add photo dialog not showing. Another site it was one of those recaptcha  pic select things  not showing

**Comment by dpacassi** [comment] 2018-09-26 14:12
@ugulz Could you please provide me the exact steps on how to reproduce the issue?
Something like
1. Start Firefox/Chrome
2. Go to the site www.domain.com
3. Click on the link "Example"
4. This site is not working

In addition, please specify which browser you are using and a screenshot of your `Disable JavaScript` settings would also be great.

I know it's a lot on information I ask for but I can't reproduce the bug on my Windows nor on my Mac machine. Thanks a lot for your support!

**Comment by dpacassi** [comment] 2018-09-27 11:06
Also, please update to the web extension version `2.3.1`. I've published it today, it may take up to one day for your browser to update it. Let me know if you're still experiencing any issues after the update and if so, how I can reproduce the issue, thanks a lot!

**Comment by ugulz** [comment] 2018-10-03 10:46
Ok I had another look and I can see its only a problem when using as whitelist. 
Some site load another document from another domain and  scripts called from that doc aren't running unless manually add that domain to whitelist.
here is url but have to be member to be able test it yourself
https://bulksell.ebay.com.au/ws/eBayISAPI.dll?SingleList&sellingMode=AddItem
had to manually add bulkedit.ebay.com.au to whitelist for all scripts on page to run

**Comment by dpacassi** [comment] 2018-10-11 08:13
@ugulz Unfortunately I can't reproduce the described issue. Here's what I've tried:
- Settings: Default state = off, Disable behavior = domain. Domain list = empty
- Browse to https://pacassi.ch/jquery.html and open console
- I only see errors about refusing to load JavaScript
- Click on the web extension icon (pacassi.ch is added to the domain list)
- I see the output of local executed JavaScript
- I see that jQuery has been successfully loaded through a CDN (from code.jquery.com)

So, when allowing a site through the web extension, it will allow that site to load external JavaScript as well.
What's not handled is if the site has iframes integrated ( https://github.com/dpacassi/disable-javascript/issues/41 ).

I'm therefor closing this issue. If you still experience a bug though, please open a new issue describing on how to exactly reproduce the error. Thanks!

**Closed by dpacassi** 2018-10-11 08:13 UTC
Labels: bug, more information needed
